name: Deploy to NeoCities
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: bcomnes/neocities-deploy@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: .
